name: "default"
cmd: "echo without command"
targets:
    - extraTargetName:
      cmd: "npm"
      name: "build-css"
      args:
        - "run"
        - "build-css"
      cwd: "/home/$USER/$PROJECT"
      env:
        PROJECT: "Proyectos/django/portfolio"
