# Generated by Django 2.0.6 on 2018-07-05 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
            options={
                'ordering': ('pub_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color', models.CharField(default='#DCDCDC', max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Char has to be Hash key and a Hexadecimal code with 6 char lenght. Example: #FFFFFF (one hash and 6 chars)', regex='^#.{6}$')])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
