# Generated by Django 2.0.6 on 2018-07-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#DCDCDC', max_length=7),
        ),
    ]
