# Generated by Django 2.0.6 on 2018-07-06 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180706_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#DCDCDC', max_length=7, validators=[django.core.validators.RegexValidator(code='nomatch', message='Char has to be Hash key and a Hexadecimal code with 6 char lenght. Example: #FFFFFF (one hash and 6 chars)', regex='^#.{6}$')]),
        ),
    ]
